"""add_missing_fields_and_tables

Revision ID: 7cb010def550
Revises: b519dd903071
Create Date: 2026-07-30 13:37:06.344586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb010def550'
down_revision = 'b519dd903071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avatar_cache', schema=None) as batch_op:
        batch_op.create_index('idx_avatar_cache_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_avatar_cache_source_url'), ['source_url'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('avatar_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatar_cache_source_url'))
        batch_op.drop_index('idx_avatar_cache_created_at')

    op.drop_table('avatar_cache')
    # ### end Alembic commands ###
