"""add database indexes for performance

Revision ID: d31988be4862
Revises: b519dd903071
Create Date: 2026-07-30 14:06:03.664349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31988be4862'
down_revision = 'b519dd903071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avatar_cache', schema=None) as batch_op:
        batch_op.create_index('idx_avatar_cache_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_avatar_cache_source_url'), ['source_url'], unique=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_resource', ['resource_type', 'resource_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.create_index('idx_plugin_status_updated', ['status', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugins_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugins_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugins_status'), ['status'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_plugin_id'), ['plugin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.alter_column(
            'is_active',
            existing_type=sa.Boolean(),
            server_default=None,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_plugin_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))

    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugins_status'))
        batch_op.drop_index(batch_op.f('ix_plugins_category_id'))
        batch_op.drop_index(batch_op.f('ix_plugins_author_id'))
        batch_op.drop_index('idx_plugin_status_updated')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('idx_audit_resource')

    with op.batch_alter_table('avatar_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatar_cache_source_url'))
        batch_op.drop_index('idx_avatar_cache_created_at')

    op.drop_table('avatar_cache')
    # ### end Alembic commands ###
